apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-service
spec:
  type: {{ .Values.environment.database.service.type }}
  ports:
  - name: database-tcp
    protocol: TCP
    port: {{ .Values.environment.database.service.port}}
    targetPort: {{ .Values.environment.database.container.port}}
  selector:
    app: {{ .Release.Name }}-database